services:
  # Frontend - Editor CTV
  - type: web
    name: ctv-render-13-02
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_ASSETS_URL
        value: https://adsmood-ctv-assets.onrender.com
      - key: VITE_API_URL
        value: https://adsmood-ctv-api.onrender.com

  # Servicio de Assets
  - type: web
    name: adsmood-ctv-assets
    env: node
    buildCommand: cd assets && npm install
    startCommand: cd assets && node dist/server.js
    pullRequestPreviewsEnabled: true
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://ctv-render-13-02.onrender.com,https://adsmood-ctv-api.onrender.com

  # API Backend
  - type: web
    name: adsmood-ctv-api
    env: docker
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    pullRequestPreviewsEnabled: true
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: adsmood-ctv-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: adsmood-ctv-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: adsmood-ctv-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: adsmood-ctv-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: adsmood-ctv-db
          property: password
      - key: DB_SSL
        value: true
      - key: ASSETS_URL
        value: https://adsmood-ctv-assets.onrender.com
      - key: FRONTEND_URL
        value: https://ctv-render-13-02.onrender.com
      - key: ALLOWED_ORIGINS
        value: https://ctv-render-13-02.onrender.com,http://localhost:3000

databases:
  # Base de datos PostgreSQL para analytics
  - name: adsmood-ctv-db
    databaseName: adsmood_ctv
    user: adsmood
    plan: free 