services:
  # Servicio Frontend
  - type: web
    name: adsmood-ctv-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      # Cache para archivos estáticos
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      # Cache para archivos de fuentes
      - path: /fonts/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      # Cache para imágenes
      - path: "*.{jpg,jpeg,png,gif,ico,svg}"
        name: Cache-Control
        value: public, max-age=31536000, immutable
      # Cache para JS y CSS
      - path: "*.{js,css}"
        name: Cache-Control
        value: public, max-age=31536000, immutable
      # Sin cache para HTML y otros archivos dinámicos
      - path: /*
        name: Cache-Control
        value: no-cache
      # Headers de seguridad
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
      - key: VITE_API_URL
        sync: false
      - key: VITE_ASSETS_URL
        value: https://adsmood-ctv-assets.onrender.com

  # Servicio de Assets (Público)
  - type: web
    name: adsmood-ctv-assets
    env: docker
    disk:
      name: assets
      mountPath: /data
      sizeGB: 10
    buildCommand: docker build -t adsmood-ctv-assets .
    startCommand: docker run -v ${VOLUME_PATH}:/data -p ${PORT}:80 adsmood-ctv-assets
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production

  # Servicio de API
  - type: web
    name: adsmood-ctv-api
    env: node
    plan: starter
    buildCommand: npm install --location=global --unsafe-perm @nestjs/cli && npm ci && npx prisma generate && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: adsmood-ctv-db
          property: connectionString
      - key: API_URL
        value: https://adsmood-ctv-api.onrender.com
      - key: ASSETS_URL
        value: https://adsmood-ctv-assets.onrender.com

databases:
  - name: adsmood-ctv-db
    plan: starter 