services:
  # Servicio Frontend
  - type: web
    name: adsmood-ctv-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      # Cache para archivos estáticos
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      # Cache para archivos de fuentes
      - path: /fonts/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      # Cache para imágenes
      - path: "*.{jpg,jpeg,png,gif,ico,svg}"
        name: Cache-Control
        value: public, max-age=31536000, immutable
      # Cache para JS y CSS
      - path: "*.{js,css}"
        name: Cache-Control
        value: public, max-age=31536000, immutable
      # Sin cache para HTML y otros archivos dinámicos
      - path: /*
        name: Cache-Control
        value: no-cache
      # Headers de seguridad
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self' https://adsmood-ctv-api.onrender.com https://adsmood-ctv-assets.onrender.com; img-src 'self' data: blob: https:; media-src 'self' blob: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
      - key: VITE_API_URL
        value: https://adsmood-ctv-api.onrender.com
      - key: VITE_ASSETS_URL
        value: https://adsmood-ctv-assets.onrender.com

  # Servicio de Assets (Público)
  - type: web
    name: adsmood-ctv-assets
    env: docker
    disk:
      name: assets
      mountPath: /data
      sizeGB: 10
    buildCommand: docker build -t adsmood-ctv-assets .
    startCommand: docker run -v ${VOLUME_PATH}:/data -p ${PORT}:80 adsmood-ctv-assets
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: VOLUME_PATH
        value: /data
      - key: STORAGE_SIZE
        value: 10GB
      - key: MAX_UPLOAD_SIZE
        value: 1073741824

  # Servicio de API
  - type: web
    name: adsmood-ctv-api
    env: node
    plan: starter
    buildCommand: npm install --location=global --unsafe-perm @nestjs/cli && npm ci && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.19.0
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: adsmood-ctv-db
          property: connectionString
      - key: DATABASE_POOL_SIZE
        value: 20
      - key: API_URL
        value: https://adsmood-ctv-api.onrender.com
      - key: ASSETS_URL
        value: https://adsmood-ctv-assets.onrender.com
      - key: FRONTEND_URL
        value: https://ctv-render-13-02.onrender.com
      - key: TRACKING_ENABLED
        value: "true"
      - key: TRACKING_BATCH_SIZE
        value: 100
      - key: TRACKING_FLUSH_INTERVAL
        value: 60000
      - key: CACHE_TTL
        value: 3600
      - key: CACHE_MAX_ITEMS
        value: 1000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://ctv-render-13-02.onrender.com,https://adsmood-ctv-assets.onrender.com
      - key: ANALYTICS_ENABLED
        value: "true"
      - key: LOG_LEVEL
        value: info
      - key: LOG_FORMAT
        value: json
      - key: METRICS_ENABLED
        value: "true"
      - key: METRICS_PREFIX
        value: adsmood_ctv
      - key: PROMETHEUS_ENABLED
        value: "true"

databases:
  - name: adsmood-ctv-db
    plan: starter
    ipAllowList: [] # Permitir todas las IPs 